version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: meu-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 818181C@ralho
      MYSQL_DATABASE: academicnetDB
    ports:
    - "3306:3306"
    cap_add:
      - SYS_NICE
